package telemetry

import (
	crypto_rand "crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	installIDFile = "install_id"
	hostIDFile    = "host_id"
)

// Identity is the pair of anonymous IDs associated with this CLI
// install. InstallID is stable across re-installs; HostID is
// rotatable via RotateHostID. Neither is tied to a machine
// fingerprint, hostname, username, or IP — both are 32 hex chars
// (16 random bytes) generated by crypto/rand.
type Identity struct {
	InstallID string
	HostID    string
}

var idRegex = regexp.MustCompile(`^[0-9a-f]{32}$`)

// generateID reads 16 bytes from r and returns the lowercase hex
// encoding. It is the test seam: tests pass a bytes.NewReader with
// known content to assert the exact hex output. Production code
// always uses crypto/rand.Reader, which never returns an error
// outside legacy Linux — the system is unsafe for any crypto
// operation in that case, so a panic is the correct behaviour.
func generateID(r io.Reader) (string, error) {
	var buf [16]byte
	if _, err := io.ReadFull(r, buf[:]); err != nil {
		return "", fmt.Errorf("read random bytes: %w", err)
	}
	return hex.EncodeToString(buf[:]), nil
}

// writeFiles persists i to <appDir>/install_id and <appDir>/host_id.
// It creates appDir if it does not exist (fresh install case).
func (i *Identity) writeFiles(appDir string) error {
	if err := os.MkdirAll(appDir, 0o755); err != nil {
		return fmt.Errorf("create app dir: %w", err)
	}
	if err := os.WriteFile(filepath.Join(appDir, installIDFile), []byte(i.InstallID), 0o644); err != nil {
		return fmt.Errorf("write install id: %w", err)
	}
	if err := os.WriteFile(filepath.Join(appDir, hostIDFile), []byte(i.HostID), 0o644); err != nil {
		return fmt.Errorf("write host id: %w", err)
	}
	return nil
}

// loadIDFile reads <appDir>/<file> and returns the trimmed contents.
// If the file does not exist, returns ("", nil) so the caller can
// decide whether to create. If the on-disk value does not match the
// 32-hex-char schema, the file is regenerated from crypto/rand and
// the fresh value is returned — identity corruption is rare but
// recoverable.
func loadIDFile(appDir, file string) (string, error) {
	path := filepath.Join(appDir, file)
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("read id file: %w", err)
	}
	value := strings.TrimSpace(string(raw))
	if idRegex.MatchString(value) {
		return value, nil
	}
	// Corrupted or hand-edited file: regenerate, persist, return.
	fresh, err := generateID(crypto_rand.Reader)
	if err != nil {
		return "", fmt.Errorf("regenerate id: %w", err)
	}
	if err := os.WriteFile(path, []byte(fresh), 0o644); err != nil {
		return "", fmt.Errorf("rewrite id file: %w", err)
	}
	return fresh, nil
}

// LoadOrCreate returns the Identity stored at <appDir>/install_id
// and <appDir>/host_id, generating and persisting a fresh random ID
// for any file that is missing. The appDir is created if it does
// not exist. Per CONTEXT, both IDs are random; the "no PII"
// guarantee is enforced by reading the IDs from disk (no machine
// fingerprint, hostname, or IP is consulted).
func LoadOrCreate(appDir string) (Identity, error) {
	install, err := loadIDFile(appDir, installIDFile)
	if err != nil {
		return Identity{}, err
	}
	host, err := loadIDFile(appDir, hostIDFile)
	if err != nil {
		return Identity{}, err
	}
	if install == "" {
		install, err = generateID(crypto_rand.Reader)
		if err != nil {
			return Identity{}, fmt.Errorf("generate install id: %w", err)
		}
	}
	if host == "" {
		host, err = generateID(crypto_rand.Reader)
		if err != nil {
			return Identity{}, fmt.Errorf("generate host id: %w", err)
		}
	}
	id := Identity{InstallID: install, HostID: host}
	if err := id.writeFiles(appDir); err != nil {
		return Identity{}, err
	}
	return id, nil
}

// RotateHostID generates a fresh host_id, overwrites
// <appDir>/host_id with it, and returns the new value. The
// install_id is not touched. The appDir is created if it does not
// exist. The returned ID is always 32 hex chars (16 random bytes
// from crypto/rand) — no PII, no fingerprint.
func RotateHostID(appDir string) (string, error) {
	fresh, err := generateID(crypto_rand.Reader)
	if err != nil {
		return "", fmt.Errorf("generate host id: %w", err)
	}
	if err := os.MkdirAll(appDir, 0o755); err != nil {
		return "", fmt.Errorf("create app dir: %w", err)
	}
	if err := os.WriteFile(filepath.Join(appDir, hostIDFile), []byte(fresh), 0o644); err != nil {
		return "", fmt.Errorf("write host id: %w", err)
	}
	return fresh, nil
}
